import random

# Predefined sentences for each category
workout_instructions = [
    "Do 4x400 meters at 75% effort with a 90-second rest between each rep.",
    "Run 6x200 meters at your maximum sustainable pace with 2 minutes of rest.",
    "Complete 3x800 meters at a tempo pace and take a 3-minute recovery between reps.",
    "Warm up for 10 minutes, then do 5x1 minute sprints at 90% effort, with 2 minutes easy jog recovery.",
    "Finish today with 4x100 meters strides to focus on speed and form.",
    "Try 5x300 meters with 1-minute rests, focusing on consistent pacing.",
    "Perform 8x100 meters at 90% effort, jogging back as recovery.",
    "Do 3x1 mile at your tempo pace, taking 5 minutes of rest in between.",
    "Start with 2x200 meters sprints and then 2x400 meters at a comfortable pace.",
    "Run 10x50 meters uphill with a walk-back recovery.",
    "Warm up for 15 minutes, then do 6x2 minutes hard, 2 minutes easy jog.",
    "Complete 4x500 meters with 3-minute recovery jogs.",
    "Do 3x1200 meters at your goal 5k pace with 4-minute recoveries.",
    "Start with a 1-mile warm-up and finish with 4x400 meters strides.",
    "Run 7x300 meters with 100-meter walking recoveries.",
    "Do a pyramid workout: 200m, 400m, 600m, 400m, 200m with 90-second rests.",
    "Complete 10x30-second sprints, jogging for 1 minute in between.",
    "Warm up, then alternate 1 minute hard, 1 minute easy for 20 minutes.",
    "Do 5x500 meters at a moderate pace, focusing on maintaining form.",
    "Run 6x150 meters sprints, taking 2 minutes rest between each."
]

response_validation = [
    "Great job sticking to the plan! Let me know how you felt during the intervals.",
    "That sounds perfect! How was your energy level during the run?",
    "Thanks for sharing! Did you feel the pace was sustainable?",
    "Good work! Were the recoveries long enough for you to feel ready?",
    "Awesome! Tell me if anything felt off or uncomfortable.",
    "You’re doing great! How was your breathing during the workout?",
    "Fantastic effort! Did the workout feel manageable overall?",
    "Nice work! Were there any points where you felt like you were struggling?",
    "Great consistency! How was your heart rate during the intervals?",
    "Superb! Did you feel strong during the last set?",
    "Well done! Was the pacing challenging but doable?",
    "That was a solid session! Do you feel ready to tackle the next workout?",
    "Great work! Did you feel like the recoveries were sufficient?",
    "Excellent effort! Would you like to adjust the pace for next time?",
    "Good job! Did you feel any tightness or discomfort anywhere?",
    "Impressive session! How did your legs feel afterward?",
    "Great training! Did you stay hydrated before and after?",
    "You’re on track! Did you hit your target times for each interval?",
    "Nice work out there! Do you feel your fitness improving?",
    "Strong finish! How was your motivation during the session?"
]

workout_feedback = [
    "Your pacing was excellent today—nice and consistent throughout!",
    "You pushed through the workout well! Keep focusing on smooth transitions between reps.",
    "Great effort! Next time, try to hold your form during the last set.",
    "Fantastic work! If the last intervals felt too hard, we can adjust the pace.",
    "Solid performance today! Remember to hydrate and stretch to recover well.",
    "Good job! Your form is improving with each session.",
    "Well done! Let’s keep building on this effort for the next workout.",
    "You nailed it! Consistency like this will pay off in the long run.",
    "Excellent job today! Your recovery times were spot on.",
    "Great session! Your ability to maintain focus is commendable.",
    "Superb! Keep tracking your progress; it’s clear you’re improving.",
    "Fantastic effort! You’re adapting well to the increased intensity.",
    "Impressive work! Your dedication is showing in your results.",
    "You crushed it today! Let’s carry this momentum forward.",
    "Outstanding performance! Your effort level was just right.",
    "Great execution! Your splits were consistent and strong.",
    "Amazing job! Your endurance is getting better each week.",
    "Fantastic consistency! Keep focusing on controlled breathing.",
    "Excellent effort! You’re mastering the art of pacing.",
    "Strong work today! Keep up this level of focus and drive."
]

gear_feedback = [
    "Your shoes seem to be holding up well—how do they feel on longer runs?",
    "If you're feeling any discomfort, it might be time to check the wear on your insoles.",
    "Consider switching to a lighter shoe for speed workouts; it might help with performance.",
    "Those new running socks seem to be a great choice for blister prevention!",
    "Your hydration pack is working well; make sure to clean it after each long run.",
    "Do your running shorts feel comfortable during longer sessions?",
    "Try adjusting the straps on your hydration vest for a better fit.",
    "Have you considered using anti-chafing balm for longer runs?",
    "If your headphones are slipping, look into sport-specific models.",
    "Check the grip on your running shoes; they should feel secure on wet surfaces.",
    "Your gear seems well-suited to your training; keep an eye on wear and tear.",
    "It might be time to replace your running shoes if you’ve logged over 300 miles.",
    "Do you feel comfortable with your current sports watch for tracking runs?",
    "Make sure your gear is weather-appropriate as conditions change.",
    "Consider testing new socks to see if they reduce hot spots on your feet.",
    "Does your hydration belt stay secure during intervals?",
    "If your sunglasses are fogging up, try anti-fog wipes before runs.",
    "Compression sleeves might help if you’re feeling calf tightness.",
    "Try using a running-specific hat for sun protection on hot days.",
    "Check if your reflective gear is visible enough for evening runs."
]

health_feedback = [
    "You're doing great! Make sure you're eating enough protein to help with recovery.",
    "Don’t forget to get 7-8 hours of sleep tonight for optimal recovery.",
    "Your hydration seems good; keep sipping water throughout the day.",
    "If you're feeling stiff, try foam rolling or yoga to loosen up your muscles.",
    "Take note of any soreness; if it persists, we may need to adjust your training plan.",
    "Make sure to incorporate rest days into your schedule to avoid overtraining.",
    "Adding more greens to your diet can help with inflammation and recovery.",
    "Stay consistent with your post-run stretches to improve flexibility.",
    "If you're feeling fatigued, consider adjusting your weekly mileage.",
    "Keep an eye on your heart rate; it’s a good indicator of overall fitness.",
    "Remember to listen to your body and avoid pushing through pain.",
    "Staying on top of your nutrition will help you recover faster after hard workouts.",
    "If you’re feeling tired, a short walk can help energize you without overexertion.",
    "Hydrate well before, during, and after your long runs.",
    "Pay attention to your mental health; a positive mindset aids performance.",
    "Add some cross-training activities to support overall fitness.",
    "Make sure you’re fueling properly before and after workouts.",
    "Regular massages or foam rolling can help prevent tightness.",
    "Track your sleep patterns to see how they impact your training.",
    "Stay consistent with your routine, but don’t hesitate to modify if needed."
]

polite_coaching = [
    "You're doing amazing; just keep up the good work!",
    "Consistency is key—every step is progress.",
    "Remember, rest days are just as important as training days.",
    "Stay positive and trust the process; you're improving every day!",
    "Your effort inspires me; keep it up!",
    "You’ve got this! Believe in yourself and your training.",
    "Small steps lead to big results; keep moving forward.",
    "Take pride in how far you’ve come already.",
    "Your determination is truly commendable; keep it up!",
    "Every run you complete brings you closer to your goals.",
    "You’re stronger than you think; trust your abilities.",
    "Keep focusing on the journey, not just the destination.",
    "Celebrate the small wins; they build momentum for bigger goals.",
    "You’re capable of amazing things; just keep going.",
    "Hard work always pays off; stay consistent.",
    "Trust the process; progress might be slow, but it’s steady.",
    "Keep challenging yourself"
]